repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: bash -lc 'if [ "$#" -gt 0 ]; then files=$(gofmt -l "$@" || true); if [ -n "$files" ]; then echo "Files need formatting:"; echo "$files"; gofmt -w "$@"; fi; fi'
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: bash -lc 'go vet ./...'
        language: system
        pass_filenames: false
        always_run: true
      - id: go-test
        name: go test
        entry: bash -lc 'GOCACHE=${GOCACHE:-$(pwd)/.pre-commit-gocache} go test ./...'
        language: system
        pass_filenames: false
        always_run: true
